import { Product } from "@/types";

const a = (name: string) => `/assets/${name}`;

export const products: Product[] = [

  /* ─────────────── WOMEN ─────────────── */
  {
    id: "w-001",
    name: "Adunola Ankara Wrap Dress",
    price: 128500,
    image: a("ankara-W1.jpg"),
    images: [a("ankara-W1.jpg"), a("ankara-W2.jpg"), a("ankara-W3.jpg")],
    gender: "women", category: "ankara",
    description: "A vibrant Ankara wrap dress with bold geometric prints. Perfect for owambes and casual outings.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    colors: ["Blue/Yellow Print", "Red/Green Print"],
    isNew: true, isFeatured: true,
    rating: 4.8, reviewCount: 124, inStock: true,
  },
  {
    id: "w-002",
    name: "Àṣà Aso-Oke Evening Gown",
    price: 165000, originalPrice: 178000,
    image: a("aso-oke-W1.jpg"),
    images: [a("aso-oke-W1.jpg"), a("aso-oke-W2.jpg"), a("aso-oke-W3.jpg")],
    gender: "women", category: "aso-oke",
    description: "Regal Aso-Oke evening gown woven by master craftsmen in Oyo State. A statement piece for every occasion.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Champagne Gold", "Royal Purple", "Ivory White"],
    isSale: true, isFeatured: true,
    rating: 4.9, reviewCount: 89, inStock: true,
  },
  {
    id: "w-003",
    name: "Ife Kaftan Maxi",
    price: 162000,
    image: a("kaftan-W1.jpg"),
    images: [a("kaftan-W1.jpg"), a("kaftan-W2.jpg")],
    gender: "women", category: "kaftan",
    description: "Flowing kaftan maxi in premium cotton blend. Effortlessly elegant for any event.",
    sizes: ["One Size", "S/M", "L/XL", "2XL/3XL"],
    colors: ["Emerald Green", "Cobalt Blue", "Burnt Orange"],
    isFeatured: true,
    rating: 4.7, reviewCount: 201, inStock: true,
  },
  {
    id: "w-004",
    name: "Remi Ankara Cord Set",
    price: 198000,
    image: a("cord-W1.jpg"),
    images: [a("cord-W1.jpg"), a("cord-W2.jpg"), a("cord-W3.jpg")],
    gender: "women", category: "cord",
    description: "Matching Ankara top and wide-leg trouser set. Mix, match, or wear together.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Purple Ankara", "Teal Ankara"],
    isNew: true, isFeatured: true,
    rating: 4.6, reviewCount: 67, inStock: true,
  },
  {
    id: "w-005",
    name: "Tinuke Ankara Peplum Blouse",
    price: 108500,
    image: a("ankara-W4.jpg"),
    images: [a("ankara-W4.jpg"), a("ankara-W5.jpg")],
    gender: "women", category: "ankara",
    description: "Chic Ankara peplum blouse with dramatic sleeves. Pair with trousers or a pencil skirt.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    colors: ["Mixed Print"],
    rating: 4.5, reviewCount: 43, inStock: true,
  },
  {
    id: "w-006",
    name: "Chioma Adire Midi Dress",
    price: 24000, originalPrice: 31000,
    image: a("adire-W1.jpg"),
    images: [a("adire-W1.jpg"), a("adire-W2.jpg")],
    gender: "women", category: "adire",
    description: "Hand-dyed adire dress with unique indigo patterns. No two pieces are exactly alike.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Indigo Blue", "Earth Tone"],
    isSale: true,
    rating: 4.8, reviewCount: 156, inStock: true,
  },
  {
    id: "w-007",
    name: "Amaka Lace Occasion Gown",
    price: 155000,
    image: a("gown-W1.jpg"),
    images: [a("gown-W1.jpg"), a("gown-W2.jpg")],
    gender: "women", category: "gown",
    description: "Stunning lace gown with intricate embroidery. The perfect bridal asoebi or owanbe gown.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Dusty Rose", "Burgundy", "Navy"],
    isFeatured: true,
    rating: 5.0, reviewCount: 34, inStock: true,
  },
  {
    id: "w-008",
    name: "Zara Adire Two-Piece Set",
    price: 129500,
    image: a("adire-W3.jpg"),
    images: [a("adire-W3.jpg"), a("adire-W4.jpg")],
    gender: "women", category: "adire",
    description: "Hand-dyed adire two-piece with unique indigo patterns. Casual luxury at its finest.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Sunset Indigo", "Deep Blue"],
    isNew: true,
    rating: 4.4, reviewCount: 28, inStock: true,
  },
  {
    id: "w-009",
    name: "Nkechi Adire Wrap Skirt",
    price: 116500,
    image: a("adire-W5.jpg"),
    images: [a("adire-W5.jpg")],
    gender: "women", category: "adire",
    description: "Artisan-dyed adire wrap skirt with adjustable tie waist. Versatile and vibrant.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Classic Indigo"],
    rating: 4.3, reviewCount: 51, inStock: true,
  },
  {
    id: "w-010",
    name: "Folake Adire cord Set",
    price: 178000, originalPrice: 52000,
    image: a("cord-W4.jpg"),
    images: [a("cord-W4.jpg"), a("cord-W5.jpg")],
    gender: "women", category: "cord",
    description: "Adire-print cord set with wide-leg trousers and matching crop top. Draped elegance for formal events.",
    sizes: ["S/M", "L/XL", "2XL/3XL"],
    colors: ["Royal Blue/Gold", "Burnt Orange/Brown"],
    isSale: true,
    rating: 4.6, reviewCount: 77, inStock: true,
  },
  {
    id: "w-011",
    name: "Yetunde Aso-Oke Bridal Cape",
    price: 172000,
    image: a("aso-oke-W4.jpg"),
    images: [a("aso-oke-W4.jpg"), a("aso-oke-W5.jpg")],
    gender: "women", category: "aso-oke",
    description: "Handwoven Aso-Oke bridal cape with gold gele. A masterpiece for your most important day.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ivory/Gold", "Blush/Silver"],
    isNew: true, isFeatured: true,
    rating: 4.9, reviewCount: 19, inStock: true,
  },
  {
    id: "w-012",
    name: "Bisi Evening Ball Gown",
    price: 168000,
    image: a("gown-W3.jpg"),
    images: [a("gown-W3.jpg")],
    gender: "women", category: "gown",
    description: "Floor-length evening ball gown in luxurious fabric. Commanding presence for red-carpet events.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Midnight Black", "Royal Blue", "Champagne"],
    rating: 4.7, reviewCount: 22, inStock: true,
  },

  /* ─────────────── MEN ─────────────── */
  {
    id: "m-001",
    name: "Emeka Grand Agbada Set",
    price: 185000,
    image: a("agbada-M1.jpg"),
    images: [a("agbada-M1.jpg"), a("agbada-M2.jpg"), a("agbada-M3.jpg")],
    gender: "men", category: "agbada",
    description: "Three-piece grand agbada set with hand embroidery. Command any room you enter.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    colors: ["White/Gold", "Sky Blue/White", "Mint Green/White"],
    isFeatured: true,
    rating: 4.9, reviewCount: 211, inStock: true,
  },
  {
    id: "m-002",
    name: "Bode Gold-Thread Agbada",
    price: 140000,
    image: a("agbada-M4.jpg"),
    images: [a("agbada-M4.jpg"), a("agbada-M5.jpg")],
    gender: "men", category: "agbada",
    description: "Prestige agbada with real gold-thread embroidery. For weddings, chieftaincy, and power.",
    sizes: ["M", "L", "XL", "2XL", "3XL"],
    colors: ["Gold/White", "Gold/Royal Blue"],
    isFeatured: true,
    rating: 5.0, reviewCount: 18, inStock: true,
  },
  {
    id: "m-003",
    name: "Chukwudi Senator Suit",
    price: 148000, originalPrice: 60000,
    image: a("senator-M1.jpg"),
    images: [a("senator-M1.jpg"), a("senator-M2.jpg"), a("senator-M3.jpg")],
    gender: "men", category: "senator",
    description: "Tailored senator suit in premium fabric. Elegant, sharp and distinctly Nigerian.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Navy Blue", "Charcoal", "Forest Green"],
    isSale: true, isFeatured: true,
    rating: 4.7, reviewCount: 88, inStock: true,
  },
  {
    id: "m-004",
    name: "Adewale Senator Two-Piece",
    price: 144000, originalPrice: 55000,
    image: a("senator-M4.jpg"),
    images: [a("senator-M4.jpg"), a("senator-M5.jpg")],
    gender: "men", category: "senator",
    description: "Crisp two-piece senator set in premium suiting. Tailored for the Nigerian professional.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Olive Green", "Brown", "Ash Grey"],
    isSale: true,
    rating: 4.6, reviewCount: 63, inStock: true,
  },
  {
    id: "m-005",
    name: "Tunde Dashiki Embroidered Shirt",
    price: 122000,
    image: a("dashiki-M1.jpg"),
    images: [a("dashiki-M1.jpg"), a("dashiki-M2.jpg")],
    gender: "men", category: "dashiki",
    description: "Bold and expressive dashiki shirt with authentic West African embroidery at the neck.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Red/Black", "Yellow/Green", "Blue/White"],
    isNew: true, isFeatured: true,
    rating: 4.6, reviewCount: 73, inStock: true,
  },
  {
    id: "m-006",
    name: "Seun Native Shirt & Trouser",
    price: 135000,
    image: a("native-shirt-M1.jpg"),
    images: [a("native-shirt-M1.jpg"), a("native-shirt-M2.jpg")],
    gender: "men", category: "native-shirt",
    description: "Matching native shirt and trouser set in soft fabric. The everyday Nigerian gentleman.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Brown", "Green", "Blue"],
    isFeatured: true,
    rating: 4.8, reviewCount: 142, inStock: true,
  },
  {
    id: "m-007",
    name: "Kola Embroidered Kaftan",
    price: 142000,
    image: a("kaftan-M1.jpg"),
    images: [a("kaftan-M1.jpg"), a("kaftan-M2.jpg")],
    gender: "men", category: "kaftan",
    description: "Flowing kaftan with gold embroidery at the chest and hem. Regal and comfortable.",
    sizes: ["M", "L", "XL", "2XL", "3XL"],
    colors: ["White/Gold", "Champagne", "Burgundy"],
    rating: 4.7, reviewCount: 55, inStock: true,
  },
  {
    id: "m-008",
    name: "Femi Kaftan & Cap Set",
    price: 139000,
    image: a("kaftan-M3.jpg"),
    images: [a("kaftan-M3.jpg")],
    gender: "men", category: "kaftan",
    description: "Complete kaftan set with matching fila cap. Traditionally inspired, effortlessly stylish.",
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["Cream/Gold", "Teal/White", "Maroon/Gold"],
    isFeatured: true,
    rating: 4.7, reviewCount: 81, inStock: true,
  },
  {
    id: "m-009",
    name: "Jide Premium Linen Senator",
    price: 138000,
    image: a("linen-M1.jpg"),
    images: [a("linen-M1.jpg")],
    gender: "men", category: "linen",
    description: "Breathable linen senator set. A timeless silhouette for the contemporary Nigerian man.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Ecru", "Slate Blue", "Khaki"],
    isNew: true,
    rating: 4.9, reviewCount: 97, inStock: true,
  },
  {
    id: "m-010",
    name: "Iyanda Royal Agbada Set",
    price: 178000,
    image: a("agbada-M2.jpg"),
    images: [a("agbada-M2.jpg"), a("agbada-M3.jpg")],
    gender: "men", category: "agbada",
    description: "Regal three-piece agbada with intricate aso-oke detailing. A statement for coronations and high-society events.",
    sizes: ["M", "L", "XL", "2XL", "3XL"],
    colors: ["Champagne/Silver", "Royal Blue/Gold", "Wine/Gold"],
    isNew: true,
    rating: 4.8, reviewCount: 42, inStock: true,
  },
  {
    id: "m-011",
    name: "Olori Classic Agbada",
    price: 168000,
    image: a("agbada-M3.jpg"),
    images: [a("agbada-M3.jpg"), a("agbada-M1.jpg")],
    gender: "men", category: "agbada",
    description: "Traditional full-flowing agbada in premium damask fabric. Classic embroidery at the chest and sleeves.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Ivory/Gold", "Ash Grey/White", "Olive/Brown"],
    isFeatured: true,
    rating: 4.7, reviewCount: 61, inStock: true,
  },
  {
    id: "m-012",
    name: "Babatunde Prestige Agbada",
    price: 150000,
    image: a("agbada-M5.jpg"),
    images: [a("agbada-M5.jpg"), a("agbada-M4.jpg")],
    gender: "men", category: "agbada",
    description: "Top-tier prestige agbada with heavy gold-thread embroidery. Handmade by our most senior artisans over 14 days.",
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["All White/Gold", "Deep Purple/Gold"],
    rating: 5.0, reviewCount: 9, inStock: true,
  },

  /* ─── WOMEN — additional products to cover all assets ─── */

  {
    id: "w-013",
    name: "Nneka Ankara Shirt Dress",
    price: 26000,
    image: a("ankara-W2.jpg"),
    images: [a("ankara-W2.jpg"), a("ankara-W3.jpg")],
    gender: "women", category: "ankara",
    description: "Relaxed Ankara shirt dress with a bold print and self-tie belt. Perfect for weekends and brunch.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    colors: ["Blue Geometric", "Orange Floral"],
    isNew: true,
    rating: 4.6, reviewCount: 38, inStock: true,
  },
  {
    id: "w-014",
    name: "Adaeze Ankara Wide-Leg Set",
    price: 134000,
    image: a("ankara-W3.jpg"),
    images: [a("ankara-W3.jpg"), a("ankara-W1.jpg")],
    gender: "women", category: "ankara",
    description: "Statement wide-leg trouser and crop top set in vibrant Ankara. Turn every entrance into an event.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Red/Gold Print", "Black/White Print"],
    isFeatured: true,
    rating: 4.7, reviewCount: 55, inStock: true,
  },
  {
    id: "w-015",
    name: "Ngozi Ankara Maxi Skirt",
    price: 121000,
    image: a("ankara-W5.jpg"),
    images: [a("ankara-W5.jpg"), a("ankara-W4.jpg")],
    gender: "women", category: "ankara",
    description: "Floor-length Ankara maxi skirt with a high waist and side split. Comfortable, elegant, Nigerian.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    colors: ["Mixed Earth Print"],
    rating: 4.5, reviewCount: 29, inStock: true,
  },
  {
    id: "w-016",
    name: "Funmi Aso-Oke Occasion Set",
    price: 188000,
    image: a("aso-oke-W2.jpg"),
    images: [a("aso-oke-W2.jpg"), a("aso-oke-W3.jpg")],
    gender: "women", category: "aso-oke",
    description: "Two-piece Aso-Oke occasion set handwoven in Iseyin. Ideal for owambe parties and family events.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Teal/Gold", "Burgundy/Silver"],
    isFeatured: true,
    rating: 4.8, reviewCount: 44, inStock: true,
  },
  {
    id: "w-017",
    name: "Abike Aso-Oke Boubou Gown",
    price: 182000, originalPrice: 195000,
    image: a("aso-oke-W3.jpg"),
    images: [a("aso-oke-W3.jpg"), a("aso-oke-W2.jpg")],
    gender: "women", category: "aso-oke",
    description: "Flowing Aso-Oke boubou gown with hand-stitched embellishments. Commanding elegance for any ceremony.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Pink/Gold", "Sky Blue/Silver"],
    isSale: true,
    rating: 4.9, reviewCount: 31, inStock: true,
  },
  {
    id: "w-018",
    name: "Shade Aso-Oke Power Suit",
    price: 169999,
    image: a("aso-oke-W5.jpg"),
    images: [a("aso-oke-W5.jpg"), a("aso-oke-W4.jpg")],
    gender: "women", category: "aso-oke",
    description: "Modern Aso-Oke power suit — blazer and wide-leg trousers. Nigerian heritage meets executive fashion.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gold/Ivory", "Deep Green/Gold"],
    isNew: true, isFeatured: true,
    rating: 5.0, reviewCount: 12, inStock: true,
  },
  {
    id: "w-019",
    name: "Toyin Kaftan Palazzo Set",
    price: 160000,
    image: a("kaftan-W2.jpg"),
    images: [a("kaftan-W2.jpg"), a("kaftan-W1.jpg")],
    gender: "women", category: "kaftan",
    description: "Silky kaftan paired with matching palazzo trousers. Breathable, beautiful and effortlessly Nigerian.",
    sizes: ["One Size", "S/M", "L/XL", "2XL/3XL"],
    colors: ["Deep Blue/Gold", "Rose Gold/Cream"],
    rating: 4.6, reviewCount: 61, inStock: true,
  },
  {
    id: "w-020",
    name: "Taiwo Lace Maxi Gown",
    price: 185000, originalPrice: 192000,
    image: a("gown-W2.jpg"),
    images: [a("gown-W2.jpg"), a("gown-W1.jpg")],
    gender: "women", category: "gown",
    description: "Luxurious lace maxi gown with a sweetheart neckline and full skirt. Made for your grandest occasions.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blush Pink", "Ivory White", "Sapphire Blue"],
    isSale: true,
    rating: 4.8, reviewCount: 27, inStock: true,
  },
  {
    id: "w-021",
    name: "Kemi Ankara cord Shorts Set",
    price: 189000,
    image: a("cord-W2.jpg"),
    images: [a("cord-W2.jpg"), a("cord-W3.jpg")],
    gender: "women", category: "cord",
    description: "Casual Ankara shorts and matching crop jacket cord. Bright, bold and made for summer festivals.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Teal Ankara", "Yellow Ankara"],
    isNew: true,
    rating: 4.4, reviewCount: 33, inStock: true,
  },
  {
    id: "w-022",
    name: "Efe Adire cord Midi Set",
    price: 183000,
    image: a("cord-W3.jpg"),
    images: [a("cord-W3.jpg"), a("cord-W2.jpg")],
    gender: "women", category: "cord",
    description: "Hand-dyed adire cord with midi skirt and wrap top. Art-to-wear for every occasion.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Indigo Blue"],
    rating: 4.5, reviewCount: 41, inStock: true,
  },
  {
    id: "w-023",
    name: "Bola Power cord",
    price: 143999,
    image: a("cord-W5.jpg"),
    images: [a("cord-W5.jpg"), a("cord-W4.jpg")],
    gender: "women", category: "cord",
    description: "Bold Ankara blazer and straight-leg trouser power cord. Nigerian boardroom meets runway energy.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    colors: ["Black/Gold Ankara", "Red/Black Ankara"],
    isFeatured: true,
    rating: 4.7, reviewCount: 58, inStock: true,
  },
  {
    id: "w-024",
    name: "Ifeoma Adire Print Gown",
    price: 126999,
    image: a("adire-W2.jpg"),
    images: [a("adire-W2.jpg"), a("adire-W1.jpg")],
    gender: "women", category: "adire",
    description: "A-line adire print gown with ruched waist and puff sleeves. Hand-dyed in classic indigo.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Classic Indigo", "Brown Earth Tone"],
    isNew: true,
    rating: 4.6, reviewCount: 47, inStock: true,
  },
  {
    id: "w-025",
    name: "Ngozi Adire Boho Dress",
    price: 122000, originalPrice: 128000,
    image: a("adire-W4.jpg"),
    images: [a("adire-W4.jpg"), a("adire-W5.jpg")],
    gender: "women", category: "adire",
    description: "Flowy bohemian adire dress with tie-dye indigo patterns. Free-spirited and uniquely Nigerian.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Deep Indigo", "Midnight Blue"],
    isSale: true,
    rating: 4.4, reviewCount: 36, inStock: true,
  },

  /* ─── MEN — additional products to cover all assets ─── */

  {
    id: "m-013",
    name: "Emeka Classic Senator Three-Piece",
    price: 152000,
    image: a("senator-M2.jpg"),
    images: [a("senator-M2.jpg"), a("senator-M3.jpg")],
    gender: "men", category: "senator",
    description: "Three-piece senator suit with embroidered pocket detailing. The Nigerian gentleman's signature look.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Ivory", "Champagne", "Stone Grey"],
    isNew: true, isFeatured: true,
    rating: 4.8, reviewCount: 72, inStock: true,
  },
  {
    id: "m-014",
    name: "Lanre Senator Agbada Fusion",
    price: 155000, originalPrice: 167999,
    image: a("senator-M3.jpg"),
    images: [a("senator-M3.jpg"), a("senator-M2.jpg")],
    gender: "men", category: "senator",
    description: "A fusion of senator tailoring and agbada flow. Modern Nigerian dressing at its most distinguished.",
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["Deep Navy", "Charcoal/Gold", "Ash/Silver"],
    isSale: true,
    rating: 4.7, reviewCount: 49, inStock: true,
  },
  {
    id: "m-015",
    name: "Biodun Embroidered Senator",
    price: 146000,
    image: a("senator-M5.jpg"),
    images: [a("senator-M5.jpg"), a("senator-M4.jpg")],
    gender: "men", category: "senator",
    description: "Clean-cut senator with intricate chest embroidery. Impeccable for office, church and events.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Sky Blue", "White/Gold", "Brown/Cream"],
    isFeatured: true,
    rating: 4.6, reviewCount: 83, inStock: true,
  },
  {
    id: "m-016",
    name: "Fela Dashiki Long Set",
    price: 128000,
    image: a("dashiki-M2.jpg"),
    images: [a("dashiki-M2.jpg"), a("dashiki-M1.jpg")],
    gender: "men", category: "dashiki",
    description: "Long dashiki shirt with matching drawstring trousers. Vibrant West African embroidery with a relaxed fit.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Orange/Black", "Purple/Gold"],
    rating: 4.5, reviewCount: 39, inStock: true,
  },
  {
    id: "m-017",
    name: "Deji Native Shirt Premium Set",
    price: 138000,
    image: a("native-shirt-M2.jpg"),
    images: [a("native-shirt-M2.jpg"), a("native-shirt-M1.jpg")],
    gender: "men", category: "native-shirt",
    description: "Luxe native shirt and trouser set with hand-stitched collar embroidery. Effortless Nigerian style.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Cream/Gold", "Sage Green", "Dusty Blue"],
    isNew: true,
    rating: 4.7, reviewCount: 64, inStock: true,
  },
  {
    id: "m-018",
    name: "Hakeem Kaftan Robe Set",
    price: 145000,
    image: a("kaftan-M2.jpg"),
    images: [a("kaftan-M2.jpg"), a("kaftan-M1.jpg")],
    gender: "men", category: "kaftan",
    description: "Full-length kaftan robe in lightweight damask with hand-embroidered borders. Royally comfortable.",
    sizes: ["M", "L", "XL", "2XL", "3XL"],
    colors: ["White/Silver", "Cream/Gold", "Navy/Gold"],
    isFeatured: true,
    rating: 4.8, reviewCount: 47, inStock: true,
  },
];

export const getFeatured = () => products.filter((p) => p.isFeatured);
export const getByGender = (g: "women" | "men") => products.filter((p) => p.gender === g);
export const getSaleItems = () => products.filter((p) => p.isSale);
export const getNewArrivals = () => products.filter((p) => p.isNew);

